# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

ccflags-y += -O3 -ffast-math

obj-$(CONFIG_FINGERPRINT_GOODIX_FOD)	+= goodix_fod/
obj-$(CONFIG_FINGERPRINT_GOODIX_TEE)	+= goodix_tee/
obj-$(CONFIG_FINGERPRINT_FPC_TEE)	+= fpc_tee/
